function displayLyric(response) {
  new Typewriter("#lyric", {
    strings: response.data.answer,
    autoStart: true,
    delay: 1,
    cursor: "",
  });
}
function generateLyric(event) {
  event.preventDefault();

  let instructionsInput = document.querySelector("#instructions");
  let apiKey = "24b9b3ae0f6ea728ao45f6et261b0962";
  let prompt = `Generate a G rated 4 line Rap song about ${instructionsInput.value} without a title  and separate each line with a <br /> At the end of the song. Sign the song 'Generated by Maya Claros for SheCodes AI' inside a <strong> element at the end of the song. Do not include a title`;
  let context =
    "User instructions: You are an expert in Hip Hop music with a talent for writing very short songs. Your mission is to generate a G rated song that is 4 lines long in basic HTML";
  let apiUrl = `https://api.shecodes.io/ai/v1/generate?prompt=${prompt}&key=${apiKey}`;

  let lyricElement = document.querySelector("#lyric");
  lyricElement.classList.remove("hidden");
  lyricElement.innerHTML = `<div class="generating">⌛️ Generating a Rap Song about ${instructionsInput.value}</div>`;

  console.log("generating lyric");
  console.log(`Prompt:${prompt}`);
  console.log(`Context: ${context}`);
  axios.get(apiUrl).then(displayLyric);
}

let lyricFormElement = document.querySelector("#lyric-generator-form");
lyricFormElement.addEventListener("submit", generateLyric);
